### ISSUE TITLE
Revisar la introducción

### ISSUE THREAD

**Issue by JJ** [analca3/StarCraft-winner-prediction#14]
Tanto en estructura como en contenido, conviene revisar la introducción. He añadido diferentes comentarios, pero debes dejar clara la motivación del trabajo, caracterizar el problema diciendo qué es exactamente Starcraft y qué lo hace diferente de otros juegos o parecido de forma que se pueda generalizar el resultado. Por ejemplo ¿qué componente aleatorio tiene?

**Comment by 29antonioac** [comment]
Uso esta issue para todo lo relativo a la introducción.

Por favor, revisa estos comentarios, así no nos dejamos ninguno.

https://github.com/analca3/StarCraft-winner-prediction/blob/master/Report/capitulos/1_Introduccion.Rnw#L17

https://github.com/analca3/StarCraft-winner-prediction/blob/master/Report/capitulos/1_Introduccion.Rnw#L69

https://github.com/analca3/StarCraft-winner-prediction/blob/master/Report/capitulos/1_Introduccion.Rnw#L110

https://github.com/analca3/StarCraft-winner-prediction/blob/master/Report/capitulos/1_Introduccion.Rnw#L151

Este no es de introducción, pero por no abrir otra issue para uno solo
https://github.com/analca3/StarCraft-winner-prediction/blob/master/Report/capitulos/3_Metodolog%C3%ADa.Rnw#L7

Mañana le echo otro vistazo (me ha quedado algo por resolver) y borraré más comentarios que han quedado resueltos. Además de volver a revisar las reglas de estilo.
