### ISSUE TITLE
Sigue habiendo errores de compilación

### ISSUE THREAD

**Issue by JJ** [analca3/StarCraft-winner-prediction#16]
![screenshot from 2017-08-26 19 39 11](https://user-images.githubusercontent.com/500/29743638-4eb5edb8-8a96-11e7-966d-3133283bce2d.png)

**Comment by JJ** [comment]
Mismo con `features.rf`y `features.nb`

**Comment by 29antonioac** [comment]
Vaya, el problema es el readme, que no está actualizado. Hace falta git lfs
y el paquete xtable de R.

Por favor, instala git lfs y el paquete xtable de R y ejecuta en el repo:

git lfs install
git lfs pull

Si el problema persiste, vuelve a clonar, por favor. En su día probaron
varias personas a compilar y sin problemas.

**Comment by JJ** [comment]
No son ficheros, son directorios con los que está dando error. No está creando correctamente el objeto features.nb que es un directorio.
Voy a compilar de nuevo a ver. Y de hecho, volví a clonar porque al hacer make me daba problemas.

**Comment by JJ** [comment]
![screenshot from 2017-08-27 19 10 16](https://user-images.githubusercontent.com/500/29752283-60be2794-8b5b-11e7-9ac7-e11cdb5a8c3f.png)
Errores diferentes ahora.

**Comment by 29antonioac** [comment]
En estos días me lo han probado bastantes compañeros. El error que te da diría que no es por el código, sino por tu versión de ggplot2, ya que la función `position_stack` (es para poner en horizontal los gráficos de barras) parece ser de la versión 2.2.0.

Puedes comprobarlo con `packageVersion("ggplot2")`. En mi caso, tengo la 2.2.1.

**Comment by JJ** [comment]
2.1.0. No estaría mal o avisar o comprobar versiones mínimas antes de hacer
el make... ¿No existe algo como requirements.txt para R?

**Comment by 29antonioac** [comment]
En su día estuve buscando y no parece haber nada en el core de R.

**Comment by JJ** [comment]
Al final he tenido que actualizar a la última versión de R también.

**Comment by 29antonioac** [comment]
Parece que se puede cerrar, entonces.

**Comment by JJ** [comment]
Si, finalmente compila.
