### ISSUE TITLE
Hay algún problema en los resultados

### ISSUE THREAD

**Issue by JJ** [analca3/StarCraft-winner-prediction#17]
En general, Random Forest es el mejor clasificador en casi cada ocasión. kNN es tan simple que se suele usar como baseline, igual que el Naïve Bayes. Y más, si usamos k=3. Convendría que hicieras diferentes particiones del conjunto y diferentes pruebas, porque los resultados son realmente sorprendentes.

**Comment by 29antonioac** [comment]
Yo también me sorprendí, ya hice varias pruebas en junio y todo debería ser
correcto.

Además, cuando hice pruebas con R en octubre, obtuve resultados similares
con 3-NN.

En cualquier caso, desde que me comentaste el problema de la
experimentación, estoy ejecutando todo de nuevo repetidas veces (5, y aún
quedan bastantes horas). A ver qué sale.

**Comment by JJ** [comment]
El 27 de agosto de 2017, 18:11, Antonio Álvarez Caballero <
notifications@github.com> escribió:

> Yo también me sorprendí, ya hice varias pruebas en junio y todo debería ser
> correcto.
>
> Además, cuando hice pruebas con R en octubre, obtuve resultados similares
> con 3-NN.
>

El problema no es tanto con eso sino con el resto. Ya te digo, Random
Forest casi siempre da buenos resultados. Normalmente tienes que hacer un
análisis de sensibilidad a diferentes parámetros para ver cómo variaría el
resultado dependiendo de los mismos.

**Comment by 29antonioac** [comment]
Por fin ha terminado la experimentación. Han salido resultados similares para los distintos conjuntos de validación.

**Comment by JJ** [comment]
*Ahora* sí puedes decir que el resultado es estadísticamente
significativo...

**Comment by 29antonioac** [comment]
70791925edea5ac7c51a2cef1b992e85471fc85d también cerraba este
