### ISSUE TITLE
Errores al descargar el repo

### ISSUE THREAD

**Issue by JJ** [analca3/StarCraft-winner-prediction#19]
```
Pointer file error: Unable to parse pointer at: "Spark-workspace/StarCraft-Analytics/measures/measures_9000/part-00000-6e804984-7748-493a-a3ea-602e27adb2c3.csv"
```
Tengo git-lfs 1.8.1. No sé si será de eso.
También sería interesante incluir el hecho de que hay que tener git-lfs instalado para descargártelo...

**Comment by 29antonioac** [comment]
Lo revisaré en casa y modificaré el readme, que estoy en la oficina ahora mismo.

**Comment by JJ** [comment]
Creo que puede ser por esto... https://github.com/git-lfs/git-lfs/issues/1828
