### ISSUE TITLE
Añadir referencia a la licencia en el código

### ISSUE THREAD

**Issue by JJ** [analca3/StarCraft-winner-prediction#20]
En comentarios, cada pieza de código debe tener una referencia al autor, licencia e indicación de a qué paquete pertenece.

**Comment by 29antonioac** [comment]
Qué quieres decir con que a qué paquete pertenece? El paquete de Scala? Es justo la primera línea, ¿es necesario ponerlo en un comentario también?

**Comment by JJ** [comment]
Antonio, hay unas reglas, siempre las mismas, para liberar código. Son
estas http://osl.ugr.es/2013/08/02/como-liberar-software/

**Comment by 29antonioac** [comment]
Ahora sí.

**Comment by JJ** [comment]
:+1:
