### ISSUE TITLE
Eliminar números mágicos del código

### ISSUE THREAD

**Issue by JJ** [analca3/StarCraft-winner-prediction#21]
Ningún código debe de llevar números mágicos. Se define una constante con un nombre significativo y se le asigna un valor. Si es posible, esas constantes deberían estar en un fichero de configuración aparte.

**Comment by 29antonioac** [comment]
Es posible (y sencillo) utilizar un fichero a parte, pero no puedo asegurar que funcione en el modo cluster de Spark, ya que mi instalación es en modo standalone. Sin testearlo, prefiero poner constantes.

**Comment by JJ** [comment]
No sé qué es el modo cluster, pero si es un modo en el que se despliega una
aplicación, es precisamente lo que doy yo en máster y grado y que TODO
programa informático debería usar: un script para desplegar la aplicación y
que pueda funcionar en cualquier modo, no sólo "en mmi portátil" En el caso
de Scala, precisamente, hay una herramienta de despliegue hecha por
Era7bioinformatics (que ahora busco). Mientras tanto, aquí sugieren
diferentes formas
https://www.reddit.com/r/scala/comments/32bn4p/how_to_deploy_scala_applications/
entre ellas herramientas genéricas como Capistrano o Fabric.

**Comment by JJ** [comment]
Este https://github.com/ohnosequences/statika

**Comment by 29antonioac** [comment]
No he dicho que no se pueda, sólo que no puedo testearlo. Scala tiene capacidad para eso utilizando la clase ConfigFactory y leyendo directamente desde un archivo de configuración

a = 1
b = 2

pero como te digo, no puedo testear que funcione lo que Spark quiere que haga (asegurarme de que el cluster mande dicho fichero a los workers con un flag al mandar la app). Puedo hacerlo sin problemas, pero no podré asegurar que funcione.

**Comment by JJ** [comment]
No te entiendo muy bien.

**Comment by 29antonioac** [comment]
Lo que quiero decir es que Scala ya tiene un modo de tener configuración a partir de fichero o de variables de entorno. Se utiliza una clase que ya tiene potencia para eso y es muy sencillo. El problema es con Spark.

En modo standalone, que es como lo tengo en mi equipo (sólo tengo una máquina), no hay ningún problema puesto que la única máquina que calcula es la master. Esta máquina tiene acceso al fichero de configuración sin problema.

En modo cluster, todos los archivos que haya que utilizar deben estar en el espacio HDFS del cluster Hadoop, para que cualquier worker del cluster pueda acceder a él. Con los datasets no hay problema puesto que lo normal es utilizar HDFS para albergarla. Pero un fichero de configuración es totalmente distinto: es algo que mandas desde tu máquina al cluster. Se puede o empaquetar en el .jar del programa (lo cual no tendría sentido, puesto que para re-empaquetar el jar, modifico las variables y compilo), o bien mandar el fichero al cluster y asegurarse de que lo manda a los workers. Si no se hace como se debe, el master verá esos ficheros, pero los workers no. En teoría es utilizando una flag de `spark-submit`,  pero como te digo, no puedo probar el modo cluster ahora mismo (no me da tiempo, básicamente), y no me gustaría subir código que no fuera directamente ejecutable en un cluster de Spark.

**Comment by JJ** [comment]
El 8 de septiembre de 2017, 18:10, Antonio Álvarez Caballero <
notifications@github.com> escribió:

> Lo que quiero decir es que Scala ya tiene un modo de tener configuración a
> partir de fichero o de variables de entorno. Se utiliza una clase que ya
> tiene potencia para eso y es muy sencillo. El problema es con Spark.
>
> En modo standalone, que es como lo tengo en mi equipo (sólo tengo una
> máquina), no hay ningún problema puesto que la única máquina que calcula es
> la master. Esta máquina tiene acceso al fichero de configuración sin
> problema.
>
> En modo cluster, todos los archivos que haya que utilizar deben estar en
> el espacio HDFS del cluster Hadoop, para que cualquier worker del cluster
> pueda acceder a él. Con los datasets no hay problema puesto que lo normal
> es utilizar HDFS para albergarla. Pero un fichero de configuración es
> totalmente distinto: es algo que mandas desde tu máquina al cluster. Se
> puede o empaquetar en el .jar del programa (lo cual no tendría sentido,
> puesto que para re-empaquetar el jar, modifico las variables y compilo), o
> bien mandar el fichero al cluster y asegurarse de que lo manda a los
> workers. Si no se hace como se debe, el master verá esos ficheros, pero los
> workers no. En teoría es utilizando una flag de spark-submit, pero como
> te digo, no puedo probar el modo cluster ahora mismo (no me da tiempo,
> básicamente), y no me gustaría subir código que no fuera directamente
> ejecutable en un cluster de Spark.
>
>
Se tendrá que desplegar al cluster HDFS entonces... Donde dices "mandas"
debes decir "despliegas". Tanto ficheros como otros servicios que
necesites.

No creo que nadie mire el código de todas formas, pero lo de "nada de
números mágicos" es una práctica básica en programación que debería
respetarse siempre...
