### ISSUE TITLE
Expresar mejor el resumen

### ISSUE THREAD

**Issue by JJ** [analca3/StarCraft-winner-prediction#8]
Con motivación, objetivos, qué se quiere hacer, qué metodología se va a seguir, qué se ha hecho, qué resultados.

**Comment by JJ** [comment]
He hecho algunos comentarios sobre el LaTeX

**Comment by 29antonioac** [comment]
Como primera revisión, a67c513b9d53d71849edae4b04147f29e122df31

Cuando me des tu aprobación @JJ , sea cuando sea, lo pasaré a inglés.

**Comment by JJ** [comment]
Empieza a pasarlo en cuanto que puedas. Mejor no hacer depender una cosa de
la otra.
