### ISSUE TITLE
Sigo sin poder compilar

### ISSUE THREAD

**Issue by JJ** [analca3/StarCraft-winner-prediction#9]
![screenshot from 2017-07-09 19 32 09](https://user-images.githubusercontent.com/500/27996198-67266910-64dd-11e7-80e8-81ae1a92b1ee.png)

**Comment by 29antonioac** [comment]
ecf657414682c4accba539c6fb29c106ad7dfa62

Además, para evitar lanzar Spark (que es bastante CPU y RAM - dependiente)
bc083cca4ed26fba2538c944917327ebd4c05818
3f7d4aef952f2803f1a9b5f66ae1a80db238cad0

Lo que conlleva modificar el módulo de Spark para sobreescribir resultados
8d94f56f2939931de3ec500acec591ce3883db7b

Y una dependencia que falta en `make install`
ed59d5cb0637c1b8be757a08028c8f86c0b738dd

Por último, hace falta Git LFS para descargar los archivos grandes. Instalar y ejecutar

```
git lfs install
git lfs pull
```

Para inicializar y coger los ficheros grandes del repositorio.
